version: '2'

services:
  kafka0:
    image: confluentinc/cp-kafka:7.3.2
    ports:
      - "9092:9092"
      - "9101:9101"
      - "9997:9997"
      - "29092:29092"
    healthcheck:
      test: nc -z localhost 9092 || exit -1
      start_period: 15s
      interval: 5s
      timeout: 10s
      retries: 10
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: 'CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT'
      KAFKA_ADVERTISED_LISTENERS: 'PLAINTEXT://kafka0:29092,PLAINTEXT_HOST://localhost:9092'
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_JMX_PORT: 9101
      KAFKA_JMX_HOSTNAME: localhost
      KAFKA_PROCESS_ROLES: 'broker,controller'
      KAFKA_NODE_ID: 1
      KAFKA_CONTROLLER_QUORUM_VOTERS: '1@kafka0:29093'
      KAFKA_LISTENERS: 'PLAINTEXT://kafka0:29092,CONTROLLER://kafka0:29093,PLAINTEXT_HOST://0.0.0.0:9092'
      KAFKA_INTER_BROKER_LISTENER_NAME: 'PLAINTEXT'
      KAFKA_CONTROLLER_LISTENER_NAMES: 'CONTROLLER'
      KAFKA_LOG_DIRS: '/tmp/kraft-combined-logs'
    volumes:
      - ./scripts/update_run.sh:/tmp/update_run.sh
    command: "bash -c 'if [ ! -f /tmp/update_run.sh ]; then echo \"ERROR: Did you forget the update_run.sh file that came with this docker-compose.yml file?\" && exit 1 ; else /tmp/update_run.sh && /etc/confluent/docker/run ; fi'"
    networks:
      - learn-firehose

  kafka-ui:
    container_name: kafka-ui
    image: provectuslabs/kafka-ui:4d03802a5dc77f6b327485484eb63106a87152b5
    ports:
      - 8080:8080
    depends_on:
      kafka0:
        condition: service_healthy
    environment:
      KAFKA_CLUSTERS_0_NAME: local
      KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS: kafka0:29092
      KAFKA_CLUSTERS_0_METRICS_PORT: 9997
      DYNAMIC_CONFIG_ENABLED: 'true'
    networks:
      - learn-firehose

  ### producer
  producer-grpc:
    container_name: producer-grpc
    image: learn-firehose:latest
    depends_on:
      kafka0:
        condition: service_healthy
    environment:
      KAFKA_HOST: kafka0
      KAFKA_PORT: 29092
      KAFKA_TOPIC_GRPC: flag_grpc
    command:
      - grpc-producer
    networks:
      - learn-firehose
  
  producer-json:
    container_name: producer-json
    image: learn-firehose:latest
    depends_on:
      kafka0:
        condition: service_healthy
    environment:
      KAFKA_HOST: kafka0
      KAFKA_PORT: 29092
      KAFKA_TOPIC_JSON: flag_json
    command:
      - json-producer
    networks:
      - learn-firehose

  ## FIREHOSE - sink log
  json-sink-log:
    container_name: json-sink-log
    image: odpf/firehose:0.7.4
    depends_on:
      kafka0:
        condition: service_healthy
    environment:
      SOURCE_KAFKA_BROKERS: kafka0:29092
      SOURCE_KAFKA_CONSUMER_GROUP_ID: json-consumer-sink-log
      SOURCE_KAFKA_TOPIC: flag_json
      SINK_TYPE: log
      SOURCE_KAFKA_CONSUMER_CONFIG_AUTO_OFFSET_RESET: latest
      INPUT_SCHEMA_DATA_TYPE: json
    networks:
      - learn-firehose

  ## Firehose - sink mongoDB
  mongo:
    image: mongo:6
    expose:
      - 27017
    networks:
        - learn-firehose
  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_URL: mongodb://mongo:27017/
    networks:
        - learn-firehose
  json-sink-mongo:
    container_name: json-sink-mongo
    image: odpf/firehose:0.7.4
    depends_on:
      kafka0:
        condition: service_healthy
    environment:
      SOURCE_KAFKA_BROKERS: kafka0:29092
      SOURCE_KAFKA_CONSUMER_GROUP_ID: json-consumer-sink-http
      SOURCE_KAFKA_TOPIC: flag_json
      SINK_TYPE: mongodb
      SOURCE_KAFKA_CONSUMER_CONFIG_AUTO_OFFSET_RESET: latest
      SINK_MONGO_CONNECTION_URLS: mongo:27017
      SINK_MONGO_DB_NAME: sink_json_db
      SINK_MONGO_COLLECTION_NAME: sink_json_coll
      SINK_MONGO_PRIMARY_KEY: id
      SINK_MONGO_INPUT_MESSAGE_TYPE: JSON
    networks:
        - learn-firehose

networks:
  learn-firehose:
    driver: "bridge"
