version: '2'

services:
  kafka0:
    image: confluentinc/cp-kafka:7.3.2
    ports:
      - "9092:9092"
      - "9101:9101"
      - "9997:9997"
      - "29092:29092"
    healthcheck:
      test: nc -z localhost 9092 || exit -1
      start_period: 15s
      interval: 5s
      timeout: 10s
      retries: 10
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: 'CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT'
      KAFKA_ADVERTISED_LISTENERS: 'PLAINTEXT://kafka0:29092,PLAINTEXT_HOST://localhost:9092'
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_JMX_PORT: 9101
      KAFKA_JMX_HOSTNAME: localhost
      KAFKA_PROCESS_ROLES: 'broker,controller'
      KAFKA_NODE_ID: 1
      KAFKA_CONTROLLER_QUORUM_VOTERS: '1@kafka0:29093'
      KAFKA_LISTENERS: 'PLAINTEXT://kafka0:29092,CONTROLLER://kafka0:29093,PLAINTEXT_HOST://0.0.0.0:9092'
      KAFKA_INTER_BROKER_LISTENER_NAME: 'PLAINTEXT'
      KAFKA_CONTROLLER_LISTENER_NAMES: 'CONTROLLER'
      KAFKA_LOG_DIRS: '/tmp/kraft-combined-logs'
    volumes:
      - ./scripts/update_run.sh:/tmp/update_run.sh
    command: "bash -c 'if [ ! -f /tmp/update_run.sh ]; then echo \"ERROR: Did you forget the update_run.sh file that came with this docker-compose.yml file?\" && exit 1 ; else /tmp/update_run.sh && /etc/confluent/docker/run ; fi'"
    networks:
      - learn-firehose

  kafka-ui:
    container_name: kafka-ui
    image: provectuslabs/kafka-ui:4d03802a5dc77f6b327485484eb63106a87152b5
    ports:
      - 8080:8080
    depends_on:
      kafka0:
        condition: service_healthy
    environment:
      KAFKA_CLUSTERS_0_NAME: local
      KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS: kafka0:29092
      KAFKA_CLUSTERS_0_METRICS_PORT: 9997
      DYNAMIC_CONFIG_ENABLED: 'true'
    networks:
      - learn-firehose

  ### producer
  producer-grpc:
    container_name: producer-grpc
    image: learn-firehose:latest
    depends_on:
      kafka0:
        condition: service_healthy
    environment:
      KAFKA_HOST: kafka0
      KAFKA_PORT: 29092
      KAFKA_TOPIC_GRPC: flag_grpc
    command:
      - grpc-producer
    networks:
      - learn-firehose
  
  producer-json:
    container_name: producer-json
    image: learn-firehose:latest
    depends_on:
      kafka0:
        condition: service_healthy
    environment:
      KAFKA_HOST: kafka0
      KAFKA_PORT: 29092
      KAFKA_TOPIC_JSON: flag_json
    command:
      - json-producer
    networks:
      - learn-firehose

networks:
  learn-firehose:
    driver: "bridge"
