version: '2'

services:
  kafka0:
    image: confluentinc/cp-kafka:7.3.2
    ports:
      - "9092:9092"
      - "9101:9101"
      - "9997:9997"
      - "29092:29092"
    healthcheck:
      test: nc -z localhost 9092 || exit -1
      start_period: 15s
      interval: 5s
      timeout: 10s
      retries: 10
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: 'CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT'
      KAFKA_ADVERTISED_LISTENERS: 'PLAINTEXT://kafka0:29092,PLAINTEXT_HOST://localhost:9092'
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_JMX_PORT: 9101
      KAFKA_JMX_HOSTNAME: localhost
      KAFKA_PROCESS_ROLES: 'broker,controller'
      KAFKA_NODE_ID: 1
      KAFKA_CONTROLLER_QUORUM_VOTERS: '1@kafka0:29093'
      KAFKA_LISTENERS: 'PLAINTEXT://kafka0:29092,CONTROLLER://kafka0:29093,PLAINTEXT_HOST://0.0.0.0:9092'
      KAFKA_INTER_BROKER_LISTENER_NAME: 'PLAINTEXT'
      KAFKA_CONTROLLER_LISTENER_NAMES: 'CONTROLLER'
      KAFKA_LOG_DIRS: '/tmp/kraft-combined-logs'
    volumes:
      - ./scripts/update_run.sh:/tmp/update_run.sh
    command: "bash -c 'if [ ! -f /tmp/update_run.sh ]; then echo \"ERROR: Did you forget the update_run.sh file that came with this docker-compose.yml file?\" && exit 1 ; else /tmp/update_run.sh && /etc/confluent/docker/run ; fi'"
    networks:
      - learn-firehose

  kafka-ui:
    container_name: kafka-ui
    image: provectuslabs/kafka-ui:4d03802a5dc77f6b327485484eb63106a87152b5
    ports:
      - 8080:8080
    depends_on:
      kafka0:
        condition: service_healthy
    environment:
      KAFKA_CLUSTERS_0_NAME: local
      KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS: kafka0:29092
      KAFKA_CLUSTERS_0_METRICS_PORT: 9997
      DYNAMIC_CONFIG_ENABLED: 'true'
    networks:
      - learn-firehose

  ### producer
  init-schema:
    container_name: init-schema
    image: learn-firehose:latest
    depends_on:
      postgre:
        condition: service_healthy
      stencil-server:
        condition: service_healthy
    environment:
      STENCIL_HOST: http://stencil-server
      STENCIL_PORT: 8000
    command:
      - init-schema
    networks:
      - learn-firehose

  producer-grpc:
    container_name: producer-grpc
    image: learn-firehose:latest
    depends_on:
      kafka0:
        condition: service_healthy
    environment:
      KAFKA_HOST: kafka0
      KAFKA_PORT: 29092
      KAFKA_TOPIC_GRPC: flag_grpc
    command:
      - grpc-producer
    networks:
      - learn-firehose
  
  producer-json:
    container_name: producer-json
    image: learn-firehose:latest
    depends_on:
      kafka0:
        condition: service_healthy
    environment:
      KAFKA_HOST: kafka0
      KAFKA_PORT: 29092
      KAFKA_TOPIC_JSON: flag_json
    command:
      - json-producer
    networks:
      - learn-firehose

  ## Stencil
  postgre:
    container_name: postgre
    image: postgres:15.2-alpine
    ports:
     - 5432:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: stencil
    healthcheck:
      test: ["CMD-SHELL", "sh -c 'pg_isready -d stencil'"]
      interval: 10s
      timeout: 3s
      retries: 3
    networks:
      - learn-firehose
  
  stencil-migration:
    container_name: stencil-migration
    image: odpf/stencil:0.3.2
    environment:
      DB_CONNECTIONSTRING: "postgres://postgres:postgres@postgre:5432/stencil?sslmode=disable"
    depends_on:
      postgre:
        condition: service_healthy
    command: ["server", "migrate"]
    networks:
      - learn-firehose
  
  stencil-server:
    container_name: stencil-server
    image: odpf/stencil:0.3.2
    environment:
      PORT: 8000
      DB_CONNECTIONSTRING: "postgres://postgres:postgres@postgre:5432/stencil?sslmode=disable"
    healthcheck:
      test: nc -z localhost 8000 || exit -1
      start_period: 15s
      interval: 5s
      timeout: 10s
      retries: 10
    depends_on:
      stencil-migration:
        condition: service_completed_successfully
      postgre:
        condition: service_healthy
    ports:
     - 8000:8000
    command: ["server", "start"]
    networks:
      - learn-firehose

  ## FIREHOSE - sink log
  json-sink-log:
    container_name: json-sink-log
    image: odpf/firehose:0.7.4
    depends_on:
      kafka0:
        condition: service_healthy
    environment:
      SOURCE_KAFKA_BROKERS: kafka0:29092
      SOURCE_KAFKA_CONSUMER_GROUP_ID: json-consumer-sink-log
      SOURCE_KAFKA_TOPIC: flag_json
      SOURCE_KAFKA_CONSUMER_CONFIG_AUTO_OFFSET_RESET: latest
      SINK_TYPE: log
      INPUT_SCHEMA_DATA_TYPE: json
    networks:
      - learn-firehose

  grpc-sink-log:
    container_name: grpc-sink-log
    image: odpf/firehose:0.7.4
    depends_on:
      kafka0:
        condition: service_healthy
      stencil-server:
        condition: service_healthy
    environment:
      SOURCE_KAFKA_BROKERS: kafka0:29092
      SOURCE_KAFKA_CONSUMER_GROUP_ID: grpc-consumer-sink-log
      SOURCE_KAFKA_TOPIC: flag_grpc
      SOURCE_KAFKA_CONSUMER_CONFIG_AUTO_OFFSET_RESET: latest
      KAFKA_RECORD_PARSER_MODE: message
      SINK_TYPE: log
      INPUT_SCHEMA_DATA_TYPE: protobuf
      INPUT_SCHEMA_PROTO_CLASS: payload.Flag
      SCHEMA_REGISTRY_STENCIL_ENABLE: true
      SCHEMA_REGISTRY_STENCIL_URLS: http://stencil-server:8000/v1beta1/namespaces/mynamespace/schemas/flagschema
    networks:
      - learn-firehose
  
  # filter log with id started with [a,b,c,d,e] character
  grpc-sink-log-abcde:
    container_name: grpc-sink-log-abcde
    image: odpf/firehose:0.7.4
    depends_on:
      kafka0:
        condition: service_healthy
      stencil-server:
        condition: service_healthy
    environment:
      SOURCE_KAFKA_BROKERS: kafka0:29092
      SOURCE_KAFKA_CONSUMER_GROUP_ID: grpc-consumer-sink-log-abcde
      SOURCE_KAFKA_TOPIC: flag_grpc
      SOURCE_KAFKA_CONSUMER_CONFIG_AUTO_OFFSET_RESET: latest
      KAFKA_RECORD_PARSER_MODE: message
      SINK_TYPE: log
      INPUT_SCHEMA_DATA_TYPE: protobuf
      INPUT_SCHEMA_PROTO_CLASS: payload.Flag
      SCHEMA_REGISTRY_STENCIL_ENABLE: true
      SCHEMA_REGISTRY_STENCIL_URLS: http://stencil-server:8000/v1beta1/namespaces/mynamespace/schemas/flagschema
      FILTER_SCHEMA_PROTO_CLASS: payload.Flag
      FILTER_DATA_SOURCE: message
      FILTER_ENGINE: JSON
      FILTER_ESB_MESSAGE_FORMAT: PROTOBUF
      FILTER_JSON_SCHEMA: '{"properties":{"id":{"pattern":"^[abcde].*$"}}}'
    networks:
      - learn-firehose

  ## Firehose - sink mongoDB
  mongo:
    image: mongo:6
    expose:
      - 27017
    networks:
        - learn-firehose

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_URL: mongodb://mongo:27017/
    networks:
        - learn-firehose

  json-sink-mongo:
    container_name: json-sink-mongo
    image: odpf/firehose:0.7.4
    depends_on:
      kafka0:
        condition: service_healthy
    environment:
      SOURCE_KAFKA_BROKERS: kafka0:29092
      SOURCE_KAFKA_CONSUMER_GROUP_ID: json-consumer-sink-http
      SOURCE_KAFKA_TOPIC: flag_json
      SINK_TYPE: mongodb
      SOURCE_KAFKA_CONSUMER_CONFIG_AUTO_OFFSET_RESET: latest
      SINK_MONGO_CONNECTION_URLS: mongo:27017
      SINK_MONGO_DB_NAME: sink_json_db
      SINK_MONGO_COLLECTION_NAME: sink_json_coll
      SINK_MONGO_PRIMARY_KEY: id
      SINK_MONGO_INPUT_MESSAGE_TYPE: JSON
    networks:
        - learn-firehose
  
  ## Firehose - sink GRPC
  consumer-grpc:
    container_name: consumer-grpc
    image: learn-firehose:latest
    environment:
      APP_PORT: 3000
    ports:
      - "3000:3000"
    command:
      - grpc-sink
    networks:
      - learn-firehose

  grpc-sink-grpc:
    container_name: grpc-sink-grpc
    image: odpf/firehose:0.7.4
    depends_on:
      kafka0:
        condition: service_healthy
    environment:
      LOG_LEVEL: debug
      SOURCE_KAFKA_BROKERS: kafka0:29092
      SOURCE_KAFKA_CONSUMER_GROUP_ID: grpc-consumer-sink-grpc
      SOURCE_KAFKA_TOPIC: flag_grpc
      SOURCE_KAFKA_CONSUMER_CONFIG_AUTO_OFFSET_RESET: latest
      SCHEMA_REGISTRY_STENCIL_ENABLE: true
      SCHEMA_REGISTRY_STENCIL_URLS: http://stencil-server:8000/v1beta1/namespaces/mynamespace/schemas/flagschema
      INPUT_SCHEMA_DATA_TYPE: protobuf
      INPUT_SCHEMA_PROTO_CLASS: payload.Flag
      SINK_TYPE: grpc
      SINK_GRPC_SERVICE_HOST: consumer-grpc
      SINK_GRPC_SERVICE_PORT: 3000
      SINK_GRPC_METHOD_URL: payload.GrpcSink/Receive
      SINK_GRPC_RESPONSE_SCHEMA_PROTO_CLASS: payload.FlagReply
    networks:
      - learn-firehose

networks:
  learn-firehose:
    driver: "bridge"
